### ISSUE TITLE
Callee argument destruction

### ISSUE THREAD

**Issue by patstew** [tringi/papers#1]
I would suggest adding callee destruction of function arguments. This would allow destructors to be elided in many cases, e.g. where the function moves from the argument. It should also improve code size, as the destructor calls are only made once rather than at every call. This would solve, in a general way, the issue with unique_ptr described here https://www.reddit.com/r/cpp/comments/degmy1/cppcon_2019_chandler_carruth_there_are_no

**Comment by tringi** [comment]
Good idea, added.
